version: '3.4'

services:  
  marvel.project.core:
    image: marvelcontainerregistry.azurecr.io/marvelprojectcore
    build:
      context: .
      dockerfile: Marvel.Project.Core\Dockerfile
  marvel.project.data:
    image: marvelcontainerregistry.azurecr.io/marvelprojectdata
    build:
      context: .
      dockerfile: Marvel.Project.Data\Dockerfile
    environment:
      CONNECTION_STRING: Server=tcp:marveldb.database.windows.net,1433;Initial Catalog=marveldb;Persist Security Info=False;User ID=sysadmin;Password=Amogelang#5;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
  marvel.project.api:
    image: marvelcontainerregistry.azurecr.io/marvelprojectapi
    build:
      context: .
      dockerfile: Marvel.Project.API\Dockerfile
    environment:
      CONNECTION_STRING: Server=tcp:marveldb.database.windows.net,1433;Initial Catalog=marveldb;Persist Security Info=False;User ID=sysadmin;Password=Amogelang#5;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
    ports:
      - 7068:443
      - 8080:80 
     

   
  marvel.project.client:
    image: marvelcontainerregistry.azurecr.io/marvelprojectclient
    build:
      context: .\Marvel.Project.Client\ 
      dockerfile: .\Dockerfile
    ports:
    - 4200:80

